name: Template for building a container images
on:
  workflow_call:
    inputs:
      CONTAINER_REGISTRY_REPO:
        description: "name of your repo or project name in your container registry"
        required: true
        type: string
      CONTAINER_LATEST_TAG:
        description: "your container latest tag, example: dev-latest"
        required: true
        type: string
      RUNNER_LABEL:
        description: "your self hosted runner's label"
        required: true
        type: string
    secrets:
      CONTAINER_REGISTRY_USERNAME:
        description: "your container registry username"
        required: true
  
env:
  IMAGE: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}/${{ inputs.CONTAINER_REGISTRY_REPO }}
jobs:
  build-scan-image:
    name: Build a container image
    runs-on: 
      - self-hosted
      - ${{ inputs.RUNNER_LABEL }}
    outputs:
      build_id: ${{ steps.prep.outputs.BUILD_ID }}
      latest_id: ${{ steps.prep.outputs.LATEST_ID }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Prepare Image Metadata
        id: prep
        run: |
          BRANCH=${GITHUB_REF##*/}
          TS=$(date +%s)
          BUILD_ID="${BRANCH}-${TS}"
          LATEST_ID=${{ inputs.CONTAINER_LATEST_TAG }}
          echo "BUILD_ID=${BUILD_ID}" >> $GITHUB_OUTPUT
          echo "LATEST_ID=${LATEST_ID}" >> $GITHUB_OUTPUT

      - name: Push Image to Container Registry
        if: success()
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: |
            ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
            ${{ env.IMAGE }}:${{ steps.prep.outputs.LATEST_ID }}