name: Template for building a container image
on:
  workflow_call:
    inputs:
      RUNNER_LABELS:
        description: "Labels for the runner. Example: 'self-hosted', 'ubuntu', 'gpu', etc."
        required: true
        type: string
    secrets:
      CONTAINER_REGISTRY_URL:
        description: "Base container registry URL (e.g. ghcr.io/username, harbor.company.com/project, docker.io/username, your.private.container.registry/project, etc)"
        required: true
      
jobs:
  build-scan-image:
    name: Build a container image
    runs-on: ${{ fromJson(format('[{0}]', inputs.RUNNER_LABELS)) }}
    outputs:
      tags: ${{ steps.metadata.outputs.tags }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Extract timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Prepare Tag Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.CONTAINER_REGISTRY_URL }}
          tags: |
            type=ref,event=branch,suffix=-latest
            type=ref,event=branch,suffix=-${{ steps.timestamp.outputs.TIMESTAMP }}
            type=semver,pattern={{version}}
            type=sha

      - name: Build Docker Image (No Push)
        if: success()
        uses: docker/build-push-action@v3
        with:
          push: false
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}