name: Template for building a container image
on:
  workflow_call:
    inputs:
      CONTAINER_LATEST_TAG:
        description: "Your container latest tag, example: dev-latest"
        required: true
        type: string
      RUNNER_LABELS:
        description: "Labels for the runner. Example: 'self-hosted', 'ubuntu', 'gpu', etc."
        required: true
        type: string
      CONTAINER_REGISTRY_URL:
        description: "Base container registry URL (e.g. ghcr.io/username, harbor.company.com/project, docker.io/username, your.private.container.registry/project, etc)"
        required: true
        type: string
      

env:
  IMAGE: ${{ inputs.CONTAINER_REGISTRY_URL }}
jobs:
  build-scan-image:
    name: Build a container image
    runs-on: ${{ fromJson(format('[{0}]', inputs.RUNNER_LABELS)) }}
    outputs:
      build_id: ${{ steps.prep.outputs.BUILD_ID }}
      latest_id: ${{ steps.prep.outputs.LATEST_ID }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Prepare Image Metadata
        id: prep
        run: |
          BRANCH=${GITHUB_REF##*/}
          TS=$(date +%s)
          BUILD_ID="${BRANCH}-${TS}"
          LATEST_ID=${{ inputs.CONTAINER_LATEST_TAG }}
          echo "BUILD_ID=${BUILD_ID}" >> $GITHUB_OUTPUT
          echo "LATEST_ID=${LATEST_ID}" >> $GITHUB_OUTPUT

      - name: Build an Container Image
        if: success()
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: |
            ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
            ${{ env.IMAGE }}:${{ steps.prep.outputs.LATEST_ID }}