name: Template for building a container image
on:
  workflow_call:
    inputs:
      CONTAINER_LATEST_TAG:
        description: "Your container latest tag, example: dev-latest"
        required: true
        type: string
      RUNNER_LABELS:
        description: "Labels for the runner. Example: 'self-hosted', 'ubuntu', 'gpu', etc."
        required: true
        type: string
      TAG_STRATEGY:
        description: "Optional: Tagging strategy ('sha', 'timestamp', 'manual')"
        required: false
        type: string
        default: "timestamp"
      MANUAL_TAG:
        description: "Optional: Used when TAG_STRATEGY is 'manual'"
        required: false
        type: string
    secrets:
      CONTAINER_REGISTRY_URL:
        description: "Base container registry URL (e.g. ghcr.io/username, harbor.company.com/project, docker.io/username, your.private.container.registry/project, etc)"
        required: true
      

env:
  IMAGE: ${{ secrets.CONTAINER_REGISTRY_URL }}
jobs:
  build-scan-image:
    name: Build a container image
    runs-on: ${{ fromJson(format('[{0}]', inputs.RUNNER_LABELS)) }}
    outputs:
      build_id: ${{ steps.prep.outputs.BUILD_ID }}
      latest_id: ${{ steps.prep.outputs.LATEST_ID }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Prepare Tag Metadata
        id: metadata
        run: |
          STRATEGY="${{ inputs.TAG_STRATEGY }}"
          BRANCH="${GITHUB_REF#refs/heads/}"
          SHORT_SHA="${GITHUB_SHA::7}"
          TIMESTAMP=$(date +%Y%m%d%H%M%S)

          if [[ "$STRATEGY" == "manual" && "${{ inputs.MANUAL_TAG }}" != "" ]]; then
            TAGS="$BRANCH-${{ inputs.MANUAL_TAG }}"
          elif [[ "$STRATEGY" == "sha" ]]; then
            TAGS="$BRANCH-$SHORT_SHA"
          elif [[ "$STRATEGY" == "timestamp" ]]; then
            TAGS="$BRANCH-$TIMESTAMP"
          else
            echo "Invalid or no tagging strategy provided. Defaulting to branch name."
            TAGS="$BRANCH"
          fi

          if [[ "$BRANCH" != "master" ]]; then
            TAGS="$TAGS,latest"
          fi

          echo "build_id=$TAGS" >> $GITHUB_OUTPUT
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Build Docker Image (No Push)
        uses: docker/build-push-action@v3
        with:
          push: false
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.created=${{ steps.metadata.outputs.build_id }}
            org.opencontainers.image.revision=${{ github.sha }}
          tags: |
            ${{ join(fromJSON('["' + steps.metadata.outputs.tags + '"]'), format('\n{0}:', env.IMAGE)) }}:${{ steps.metadata.outputs.build_id }}