name: Template for Gosec Scan
description: |
  This workflow is used to run a Gosec scan on the codebase.
  It requires a Gosec binary to be available in the environment.
  The scan will be performed on a self-hosted runner labeled 'ubuntu', 'gpu', etc.
on:
  workflow_call:
    inputs:
      RUNNER_LABELS:
        description: "Labels for the runner. Example: 'self-hosted', 'ubuntu', 'gpu', etc."
        required: true
        type: string
        
jobs:
  gosec-scan:
    name: Gosec Scan
    runs-on: ${{ fromJson(format('[{0}]', inputs.RUNNER_LABELS)) }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-no-fail -fmt sarif -out gosec.sarif ./...'

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gosec.sarif