name: Template for Sonarqube Scan
description: |
  This workflow is used to run a Sonarqube scan on the codebase.
  It requires a Sonarqube server URL and a token for authentication.
  The scan will be performed on a self-hosted runner labeled 'ubuntu', 'gpu', 'etc'.
on:
  workflow_call:
    inputs:
      SONAR_HOST_URL:
        description: "sonarqube host url. example http://your-sonarqube-server:9000"
        required: true
        type: string
      RUNNER_LABELS:
        description: "Labels for the runner. Example: 'self-hosted', 'ubuntu', 'gpu', etc."
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        description: "Sonarqube token to check code quality"
        required: true
      
jobs:
  sonarqube-scan:
    name: Sonarqube Scan
    runs-on: ${{ fromJson(format('[{0}]', inputs.RUNNER_LABELS)) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ inputs.SONAR_HOST_URL }}
